### ISSUE TITLE
Sound support?

### ISSUE THREAD

**Issue by raphael** [longsleep/linux_patches#1]
I wasjust  wondering if you were planning on adding a patch for sound support?

**Comment by longsleep** [comment]
What do you mean? All trees have sound. What platform does not work?

**Comment by raphael** [comment]
I don't have sound on my Pixel 2 running 4.1rc7. I don't see the chromium Broadwell RT5677 patches in the main line. For example the [bdw-rt5677](https://chromium.googlesource.com/chromiumos/third_party/kernel-next/+/chromeos-sound-3.14/sound/soc/intel/bdw-rt5677.c) driver seems to be missing.

**Comment by raphael** [comment]
I just realized your patches are probably for the the 2013 Pixel... oh well :)

**Comment by longsleep** [comment]
Yeah :) sorry for that. I do not have a Pixel 2 so i cannot help on that very much.
